# Generated by Django 5.1.7 on 2025-07-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('fiche', 'Fiche'), ('image', 'Image'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de document'),
        ),
    ]
