# Generated by Django 5.1.7 on 2025-07-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0003_convert_planning_to_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si coché, le document sera visible par tous les utilisateurs', verbose_name='Document public'),
        ),
    ]
