# Generated by Django 5.1.7 on 2025-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_app', '0004_document_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Format: +33123456789 ou 0123456789', max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
