"""
Django settings for espace_client_app project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-espace-client-secret-key-change-in-production'
DEBUG = False
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'documents_app',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'storages',
]
'''
AWS_ACCESS_KEY_ID = '0057a9e8241d8490000000001'  # keyID Backblaze
AWS_SECRET_ACCESS_KEY = 'K005XBcr7UY6enLUmbQydRXYgCGon9k'  # applicationKey Backblaze
AWS_STORAGE_BUCKET_NAME = 'mes-docs'
AWS_S3_REGION_NAME = 'us-east-005'  # selon la région donnée par Backblaze
AWS_S3_ENDPOINT_URL = 'https://s3.us-east-005.backblazeb2.com'  # Endpoint S3 exact
AWS_QUERYSTRING_AUTH = False
'''
DROPBOX_OAUTH2_TOKEN = 'sl.u.AF7Iw-hswAS2GLIGk-mM6rBK4LwlKlIxIiq7DbRkMjORPfFCcB9iM59cj2LDDNh004DNoyKIH9IM3fgpI-bE1wMa05M7PiQBhS0ChFsN2OtqONtRh64HsUlOIB4zrdpKd9awgia_JqbOcc7kX7lMjb2i0Bco1S6U5AHQ6FIeYcbV0bJK0uRGpxa8U-JsmdfosOqBu1qfVWFiCIyGsrMOFaH7tKfOFxJJVSK4_fjQpxa04Yq9k9_l3JXcw8wz2ngBLR3ngmI_K4eg3VbJJqsg6FZrOpTX_IUmmUnSbV-qCEtr1U4jC2E0fKlwz2DOB4xa2nYUU6eV7UffEk6NRamQ2Z_SO9DzepG0dsUxkgW7Nkya_6lFNgr2qKvcCvFzyw2Sk4K0hrnOl2l9hTUxjCSeWrQzymSD6I4F1Ih0qiH4A3ZJK7tNor_EkkIGStIbQE5q8qF20ysds9dttiyh1s-MmM_rXe07EhpVT7LG-50QQDv-19K5-UiTehQUI4yMo5QRMNxQbkPShIeVcKk33MA5gPc1STLAnBYFz5XXdQzQ5FwmTNChC01H5SjZhYAGlGGSBnnEt5iHn3125gUub2uA7Q9F7FaaatzDm2NlEGIckQgu7t5sP_MMZitCL5sJzmSlzrxbrXleXrj2eaBWFsVg5Rxgj6jpmBtQ20PN3T9uBJAbyiG6a9JbR6RsBWioZ_QJIdu2DIGvrTjvfYzdswTnrSe9L7GNFESNiLh429ZY2kA8RD8x4lqC6bPQCBQ9sqPC7yH_P3kW0_fO3HGT3A5fYbTNkOHsoOg10vpiL-JmBhCuDxAbpJiNjtSbSTzoH1idwfG3Hhpc99mXZ99rsW38tmVALufpcBrzBV9yi19hFfgyHLG54AP8TroakRvJHg8vuBRB1abuEOUuJCID0OH7K74aQyNI7RoYq6D92vuPPawb9-vE45HBJl9bzN1f3tU3Vmukq6XNat_Ij_v38xFB2WEXzBoevSXwT2Zuaok_e9Mx3nVUYdQuo75DHnp_oecgPHJ3ZfbvN_PT7PN3kmahl3CjqZhx-Jref0x0coCtQFLygrTJPf6Ipv0vHrbn8o4vjXlmoDvFjkQjVxbDiWzgp_6qEcdrdXtTTCLpQmPmZSsxCi-qI4Lo580GF4N2Wyf_Pjes-lBIwKrNnN0yhLO64rud6V6KcV3feyiB-YrhvVxJRR6vRm5seIf2zkpN4eRPQp-ri1AIRd97BcXp0a2Qws1W5ISImNhB4c8qPwYHBDVLMkg2vMv0P4bsRpy2t63jwnorBW_XTnbJooNpXeheHUu3mA-uFe6_XuUvc4P9Xx8xfqeXoRePvgF5TYDoJHQFwarzmRiCq_yibP8HzWTVn3g6WgWapU5L5LZ-PfHDGe0ULC4Ti_lW7zDu_aRQvlw9sCXEXBSl3JeUZKQjB_lNosD03B__bx5qAFdKlTURQRgj9PkGmY-DU594BEoqnRSHDYY' # depuis env
DROPBOX_ROOT_PATH = "/media"  # dossier de stockage dans Dropbox

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'espace_client_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'espace_client_app.wsgi.application'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.dropbox.DropBoxStorage",
        "OPTIONS": {
            "oauth2_access_token": DROPBOX_OAUTH2_TOKEN,
            "root_path": DROPBOX_ROOT_PATH,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'koyebdb',
        'USER': 'koyeb-adm',
        'PASSWORD': 'npg_mphVJMv0SzC4',
        'HOST': 'ep-long-sound-a2otkrv1.eu-central-1.pg.koyeb.app',
        'OPTIONS': {'sslmode': 'require'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Modèle utilisateur personnalisé
AUTH_USER_MODEL = 'documents_app.CustomUser'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CORS settings
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    "https://espace-client-frontend-seven.vercel.app",
    "https://espace-client-frontend-seven.vercel.app",
]
CORS_ALLOW_CREDENTIALS = True



# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100  # Augmenter pour afficher plus de documents
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
}
